import os
import sys

# Set required environment variables BEFORE any app imports
os.environ.setdefault("TELEGRAM_API_ID", "12345")
os.environ.setdefault("TELEGRAM_API_HASH", "abcdef1234567890abcdef1234567890")
os.environ.setdefault("TELEGRAM_BOT_TOKEN", "123456:TESTTOKEN")
os.environ.setdefault("TELEGRAM_STORAGE_CHANNEL_ID", "-1001234567890")
os.environ.setdefault("TELEGRAM_HELPER_BOT_TOKENS", "")
os.environ.setdefault("JWT_SECRET", "testsecret123456789012345678901234")
os.environ.setdefault("DATABASE_URL", "sqlite+aiosqlite:////tmp/test.db")
os.environ.setdefault("DEBUG_PASSWORD", "testdebug")
os.environ.setdefault("WEB_BASE_URL", "http://localhost:7680")
os.environ.setdefault("GDRIVE_CLIENT_ID", "")
os.environ.setdefault("GDRIVE_CLIENT_SECRET", "")
os.environ.setdefault("OPENSUBTITLES_API_KEY", "")
os.environ.setdefault("GRAB_GROUP_USERNAME", "")
os.environ.setdefault("GRAB_BOT_USERNAME", "")
os.environ.setdefault("GRAB_BOT_USERNAMES", "")
os.environ.setdefault("SUBTITLE_LANGUAGES", "en")
os.environ.setdefault("SUBTITLE_PROVIDERS", "podnapisi,tvsubtitles,addic7ed")
os.environ.setdefault("SERVER_PORT", "7680")
os.environ.setdefault("TELEGRAM_CLIENT_CONCURRENCY", "5")
os.environ.setdefault("STREAM_BATCH_SIZE", "5")
os.environ.setdefault("STREAM_MAX_CONCURRENT", "3")
os.environ.setdefault("STREAM_RAM_PER_VIDEO_MB", "200")
os.environ.setdefault("STREAM_INFLIGHT_MB", "200")
os.environ.setdefault("STREAM_PREFETCH_AHEAD_MB", "128")
os.environ.setdefault("STREAM_PREFETCH_CONCURRENCY", "1")
os.environ.setdefault("DISK_CACHE_DIR", "/tmp/test_vcache")
os.environ.setdefault("DISK_CACHE_ENABLED", "1")
os.environ.setdefault("DISK_CACHE_TTL", "1800")
os.environ.setdefault("DISK_CACHE_MAX_BYTES", "8589934592")
os.environ.setdefault("DISK_CACHE_PER_VIDEO_BYTES", "2147483648")
os.environ.setdefault("MEMORY", "3Gi")
os.environ.setdefault("OOM_THRESHOLD_PCT", "90")

# Add backend to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))